const std = @import("std");
const testing = std.testing;
const Allocator = std.mem.Allocator;

const sema = @import("sema.zig");
const ast = @import("ast.zig");
const trie = @import("trie.zig");
const match_compiler = @import("codegen/match.zig");
const constructors = @import("codegen/constructors.zig");
const extractors = @import("codegen/extractors.zig");
const ident = @import("codegen/ident.zig");

/// Code generation options.
pub const CodegenOptions = struct {
    /// Prefix for generated functions.
    prefix: []const u8 = "",
    /// Include debug comments.
    debug_comments: bool = false,
    /// Extra Zig preamble to inject after std import.
    preamble: []const u8 = "",
};

/// Zig code generator for ISLE rules.
pub const Codegen = struct {
    /// Type environment.
    typeenv: *const sema.TypeEnv,
    /// Term environment.
    termenv: *const sema.TermEnv,
    /// Compiled rules.
    rules: []const sema.Rule,
    /// Output buffer.
    output: std.ArrayList(u8),
    /// Allocator.
    allocator: Allocator,

    const Self = @This();

    const TermSignature = struct {
        params: []const sema.TypeId,
        ret_ty: sema.TypeId,
    };

    fn getTermSignature(self: *const Self, term: sema.Term) TermSignature {
        _ = self;
        return switch (term.kind) {
            .decl => |d| .{ .params = d.arg_tys, .ret_ty = d.ret_ty },
            .extractor => |e| .{ .params = e.arg_tys, .ret_ty = e.ret_ty },
            .extern_func => |f| .{ .params = f.arg_tys, .ret_ty = f.ret_ty },
        };
    }

    pub fn init(
        allocator: Allocator,
        typeenv: *const sema.TypeEnv,
        termenv: *const sema.TermEnv,
        rules: []const sema.Rule,
    ) Self {
        return .{
            .typeenv = typeenv,
            .termenv = termenv,
            .rules = rules,
            .output = std.ArrayList(u8){},
            .allocator = allocator,
        };
    }

    pub fn deinit(self: *Self) void {
        self.output.deinit(self.allocator);
    }

    /// Generate Zig code from the compiled rules.
    pub fn generate(self: *Self, options: CodegenOptions) ![]const u8 {
        self.output.clearRetainingCapacity();
        try self.emitPreamble(options);
        try self.emitContextStubs();
        try self.emitExternWrappers();
        try self.emitExtractors();
        try self.emitConstructors();
        return self.output.items;
    }

    fn emitPreamble(self: *Self, options: CodegenOptions) !void {
        const writer = self.output.writer(self.allocator);
        try writer.writeAll(
            \\// Auto-generated by ISLE compiler
            \\const std = @import("std");
            \\
            \\
        );
        if (options.preamble.len != 0) {
            try writer.writeAll(options.preamble);
            if (options.preamble[options.preamble.len - 1] != '\n') {
                try writer.writeByte('\n');
            }
            try writer.writeByte('\n');
        }
        try self.emitTupleTypes();
    }

    fn emitTupleTypes(self: *Self) !void {
        const writer = self.output.writer(self.allocator);
        for (self.typeenv.types.items) |ty| {
            if (ty != .tuple) continue;
            const tuple = ty.tuple;
            try writer.writeAll("pub const ");
            try self.writeIdent(writer, self.typeenv.symName(tuple.name));
            try writer.writeAll(" = struct {\n");
            for (tuple.fields, 0..) |field_ty, i| {
                try writer.print("    field{d}: ", .{i});
                try self.writeTy(writer, field_ty);
                try writer.writeAll(",\n");
            }
            try writer.writeAll("};\n\n");
        }
    }

    fn emitContextStubs(self: *Self) !void {
        if (self.termenv.externs.count() == 0) return;
        const writer = self.output.writer(self.allocator);
        try writer.writeAll("pub const Context = struct {\n");
        var it = self.termenv.externs.iterator();
        while (it.next()) |entry| {
            const term_id = entry.key_ptr.*;
            const ext = entry.value_ptr.*;
            const term = self.termenv.getTerm(term_id);
            const sig = self.getTermSignature(term);

            if (ext.constructor) |func_sym| {
                const func_name = self.typeenv.symName(func_sym);
                try writer.writeAll("    pub fn ");
                try self.writeIdent(writer, func_name);
                try writer.writeAll("(\n");
                try writer.writeAll("        self: *Context,\n");
                for (sig.params, 0..) |arg_ty, i| {
                    try writer.print("        arg{d}: ", .{i});
                    try self.writeTy(writer, arg_ty);
                    try writer.writeAll(",\n");
                }
                const is_partial = term.kind == .decl and term.kind.decl.partial;
                const ret_prefix = if (is_partial) "!?" else "!";
                try writer.writeAll("    ) ");
                try writer.writeAll(ret_prefix);
                try self.writeTy(writer, sig.ret_ty);
                try writer.writeAll(" {\n");
                try writer.writeAll("        _ = self;\n");
                for (sig.params, 0..) |_, i| {
                    try writer.print("        _ = arg{d};\n", .{i});
                }
                try writer.writeAll("        return error.Unimplemented;\n");
                try writer.writeAll("    }\n\n");
            }

            if (ext.extractor) |func_sym| {
                const func_name = self.typeenv.symName(func_sym);
                try writer.writeAll("    pub fn ");
                try self.writeIdent(writer, func_name);
                try writer.writeAll("(\n");
                try writer.writeAll("        self: *Context,\n");
                try writer.writeAll("        input: ");
                try self.writeTy(writer, sig.ret_ty);
                try writer.writeAll(",\n");
                try writer.writeAll("    ) !?");
                try self.emitExtractorOutType(writer, sig.params, sig.ret_ty);
                try writer.writeAll(" {\n");
                try writer.writeAll("        _ = self;\n");
                try writer.writeAll("        _ = input;\n");
                try writer.writeAll("        return error.Unimplemented;\n");
                try writer.writeAll("    }\n\n");
            }
        }
        try writer.writeAll("    pub fn recordRule(self: *Context, rule_name: []const u8) void {\n");
        try writer.writeAll("        _ = self;\n");
        try writer.writeAll("        _ = rule_name;\n");
        try writer.writeAll("    }\n\n");
        try writer.writeAll("};\n\n");
    }

    fn emitExternWrappers(self: *Self) !void {
        const writer = self.output.writer(self.allocator);
        var it = self.termenv.externs.iterator();
        while (it.next()) |entry| {
            const term_id = entry.key_ptr.*;
            const ext = entry.value_ptr.*;
            const term = self.termenv.getTerm(term_id);
            const term_name = self.typeenv.symName(term.name);
            const sig = self.getTermSignature(term);

            if (ext.constructor) |func_sym| {
                const func_name = self.typeenv.symName(func_sym);
                const ret_prefix = if (term.kind == .decl and term.kind.decl.partial) "!?" else "!";
                try writer.writeAll("\npub fn ");
                try self.writePref(writer, "constructor_", term_name);
                try writer.writeAll("(\n");
                try writer.writeAll("    ctx: *Context,\n");
                for (sig.params, 0..) |arg_ty, i| {
                    try writer.print("    arg{d}: ", .{i});
                    try self.writeTy(writer, arg_ty);
                    try writer.writeAll(",\n");
                }
                try writer.writeAll(") ");
                try writer.writeAll(ret_prefix);
                try self.writeTy(writer, sig.ret_ty);
                try writer.writeAll(" {\n");
                try writer.writeAll("    return ctx.");
                try self.writeIdent(writer, func_name);
                try writer.writeAll("(");
                for (sig.params, 0..) |_, i| {
                    if (i > 0) try writer.writeAll(", ");
                    try writer.print("arg{d}", .{i});
                }
                try writer.writeAll(");\n}\n");
            }

            if (ext.extractor) |func_sym| {
                const func_name = self.typeenv.symName(func_sym);
                try writer.writeAll("\npub fn ");
                try self.writePref(writer, "extractor_", term_name);
                try writer.writeAll("(\n");
                try writer.writeAll("    ctx: *Context,\n");
                try writer.writeAll("    input: ");
                try self.writeTy(writer, sig.ret_ty);
                try writer.writeAll(",\n");
                try writer.writeAll(") !?");
                try self.emitExtractorOutType(writer, sig.params, sig.ret_ty);
                try writer.writeAll(" {\n");
                try writer.writeAll("    return ctx.");
                try self.writeIdent(writer, func_name);
                try writer.writeAll("(input);\n}\n");
            }
        }
    }

    fn emitExtractors(self: *Self) !void {
        var gen = extractors.ExtractorCodegen.init(self.allocator, self.typeenv, self.termenv);
        defer gen.deinit();

        for (self.termenv.terms.items) |term| {
            if (term.kind != .extractor) continue;
            const code = try gen.generateExtractor(term.id);
            try self.output.appendSlice(self.allocator, code);
        }
    }

    fn emitConstructors(self: *Self) !void {
        var term_rules = std.AutoHashMap(sema.TermId, std.ArrayList(usize)).init(self.allocator);
        defer {
            var it = term_rules.valueIterator();
            while (it.next()) |list| {
                list.deinit(self.allocator);
            }
            term_rules.deinit();
        }

        for (self.rules, 0..) |rule, i| {
            const term_id = switch (rule.pattern) {
                .term => |t| t.term_id,
                else => continue,
            };
            const entry = try term_rules.getOrPut(term_id);
            if (!entry.found_existing) {
                entry.value_ptr.* = std.ArrayList(usize){};
            }
            try entry.value_ptr.append(self.allocator, i);
        }

        for (self.termenv.terms.items) |term| {
            if (term.kind != .decl) continue;
            if (self.termenv.getExtern(term.id)) |ext| {
                if (ext.constructor != null) continue;
            }
            const entry = try term_rules.getOrPut(term.id);
            if (!entry.found_existing) {
                entry.value_ptr.* = std.ArrayList(usize){};
            }
        }

        var mc = match_compiler.MatchCompiler.init(self.allocator, self.typeenv, self.termenv);
        var ctor_gen = try constructors.ConstructorGen.init(self.allocator, self.typeenv, self.termenv);
        var emitted = std.StringHashMap(void).init(self.allocator);
        defer emitted.deinit();
        defer ctor_gen.deinit();

        var it = term_rules.iterator();
        while (it.next()) |entry| {
            const term_id = entry.key_ptr.*;
            const indices = entry.value_ptr.items;
            const term = self.termenv.getTerm(term_id);

            if (term.kind != .decl) continue;
            if (self.termenv.getExtern(term_id)) |ext| {
                if (ext.constructor != null) continue;
            }
            const term_name = self.typeenv.symName(term.name);
            if (emitted.contains(term_name)) continue;
            try emitted.put(term_name, {});

            std.mem.sort(usize, indices, self.rules, ruleIndexLess);

            var rules = std.ArrayList(sema.Rule){};
            defer rules.deinit(self.allocator);
            for (indices) |idx| {
                try rules.append(self.allocator, self.rules[idx]);
            }

            var ruleset = try mc.buildRuleSetForTerm(term_id, rules.items);
            defer ruleset.deinit();

            const code = try ctor_gen.genConstructor(term_id, &ruleset);
            try self.output.appendSlice(self.allocator, code);
        }
    }

    fn ruleIndexLess(rules: []const sema.Rule, a: usize, b: usize) bool {
        const pa = rules[a].prio;
        const pb = rules[b].prio;
        if (pa == pb) return a < b;
        return pa > pb;
    }

    fn emitRuleFunctions(self: *Self, options: CodegenOptions) !void {
        const writer = self.output.writer(self.allocator);

        // Group rules by term
        var term_rules = std.AutoHashMap(sema.TermId, std.ArrayList(usize)).init(self.allocator);
        defer {
            var it = term_rules.valueIterator();
            while (it.next()) |list| {
                list.deinit(self.allocator);
            }
            term_rules.deinit();
        }

        for (self.rules, 0..) |rule, i| {
            const term_id = switch (rule.pattern) {
                .term => |t| t.term_id,
                else => continue,
            };

            const entry = try term_rules.getOrPut(term_id);
            if (!entry.found_existing) {
                entry.value_ptr.* = std.ArrayList(usize){};
            }
            try entry.value_ptr.append(self.allocator, i);
        }

        // Generate a function for each term
        var it = term_rules.iterator();
        while (it.next()) |entry| {
            const term_id = entry.key_ptr.*;
            const rule_indices = entry.value_ptr.items;

            const term = self.termenv.getTerm(term_id);
            const term_name = self.typeenv.symName(term.name);

            // Function signature
            try writer.writeAll("/// Generated lowering for ");
            try writer.writeAll(term_name);
            try writer.writeAll("\n");
            try writer.writeAll("pub fn ");
            try self.writePref(writer, options.prefix, term_name);
            try writer.writeAll("(");

            // Generate parameters based on term signature
            const arg_tys = switch (term.kind) {
                .decl => |d| d.arg_tys,
                .extractor => |e| e.arg_tys,
                .extern_func => |e| e.arg_tys,
            };

            for (arg_tys, 0..) |arg_ty, idx| {
                try writer.print("arg{d}: ", .{idx});
                try self.writeTy(writer, arg_ty);
                if (idx < arg_tys.len - 1) {
                    try writer.writeAll(", ");
                }
            }

            const ret_ty = switch (term.kind) {
                .decl => |d| d.ret_ty,
                .extractor => |e| e.ret_ty,
                .extern_func => |e| e.ret_ty,
            };
            try writer.writeAll(") ");
            try self.writeTy(writer, ret_ty);
            try writer.writeAll(" {\n");

            // Emit rules for this term
            for (rule_indices, 0..) |rule_idx, i| {
                const rule = self.rules[rule_idx];

                if (options.debug_comments) {
                    try writer.print("    // Rule {d}\n", .{rule_idx});
                }

                // For now, just emit a simple return statement
                // Full implementation would generate pattern matching
                if (i == 0) {
                    try self.emitRuleBody(rule, 4);
                }
            }

            // Default return for unmatched patterns
            try writer.writeAll("    return error.NoMatch;\n");
            try writer.writeAll("}\n\n");
        }
    }

    fn emitRuleBody(self: *Self, rule: sema.Rule, indent: usize) !void {
        const writer = self.output.writer(self.allocator);

        // Emit pattern matching
        try self.emitIndent(indent);
        try writer.writeAll("// Pattern: ");
        try self.emitPattern(rule.pattern);
        try writer.writeByte('\n');

        // Emit expression evaluation
        try self.emitIndent(indent);
        try writer.writeAll("return ");
        try self.emitExpr(rule.expr);
        try writer.writeAll(";\n");
    }

    fn emitPattern(self: *Self, pattern: sema.Pattern) !void {
        const writer = self.output.writer(self.allocator);

        switch (pattern) {
            .var_pat => |v| {
                const name = self.typeenv.symName(v.name);
                try self.writeIdent(writer, name);
            },
            .term => |t| {
                const term = self.termenv.getTerm(t.term_id);
                const name = self.typeenv.symName(term.name);
                try writer.writeAll("(");
                try self.writeIdent(writer, name);
                for (t.args) |arg| {
                    try writer.writeByte(' ');
                    try self.emitPattern(arg);
                }
                try writer.writeByte(')');
            },
            else => {
                try writer.writeAll("<pattern>");
            },
        }
    }

    fn emitExpr(self: *Self, expr: sema.Expr) !void {
        const writer = self.output.writer(self.allocator);

        switch (expr) {
            .var_expr => |v| {
                const name = self.typeenv.symName(v.name);
                try self.writeIdent(writer, name);
            },
            .term => |t| {
                const term = self.termenv.getTerm(t.term_id);
                const name = self.typeenv.symName(term.name);
                try self.writeIdent(writer, name);
                try writer.writeByte('(');
                for (t.args, 0..) |arg, i| {
                    if (i > 0) try writer.writeAll(", ");
                    try self.emitExpr(arg);
                }
                try writer.writeByte(')');
            },
            else => {
                try writer.writeAll("error.Unimplemented");
            },
        }
    }

    fn emitIndent(self: *Self, count: usize) !void {
        const writer = self.output.writer(self.allocator);
        var i: usize = 0;
        while (i < count) : (i += 1) {
            try writer.writeByte(' ');
        }
    }

    /// Optimize rule ordering by sorting by priority and specificity.
    /// Higher priority rules come first, and within each priority group,
    /// more specific patterns come before general ones.
    pub fn optimizeMatches(self: *Self, rule_indices: []usize) !void {
        if (rule_indices.len <= 1) return;

        // Sort by composite key: (priority desc, specificity desc)
        const Context = struct {
            rules: []const sema.Rule,
            codegen: *const Codegen,

            fn lessThan(ctx: @This(), a_idx: usize, b_idx: usize) bool {
                const a = ctx.rules[a_idx];
                const b = ctx.rules[b_idx];

                // First: Higher priority comes first
                if (a.prio != b.prio) {
                    return a.prio > b.prio;
                }

                // Within same priority: More specific patterns first
                const a_score = ctx.codegen.specificityScore(a.pattern);
                const b_score = ctx.codegen.specificityScore(b.pattern);
                return a_score > b_score;
            }
        };

        const ctx = Context{ .rules = self.rules, .codegen = self };
        std.mem.sort(usize, rule_indices, ctx, Context.lessThan);
    }

    /// Compute specificity score for a pattern.
    /// Higher score = more specific pattern.
    fn specificityScore(self: *const Self, pattern: sema.Pattern) usize {
        return switch (pattern) {
            // Constant patterns are most specific
            .const_bool, .const_int => 100,

            // Constructor patterns: base score + sum of argument scores
            .term => |t| blk: {
                var score: usize = 50;
                for (t.args) |arg| {
                    score += self.specificityScore(arg);
                }
                break :blk score;
            },

            // Variable bindings: medium specificity
            .var_pat => 10,

            // And-patterns: sum of sub-pattern scores
            .and_pat => |a| blk: {
                var score: usize = 0;
                for (a.subpats) |subpat| {
                    score += self.specificityScore(subpat);
                }
                break :blk score;
            },

            // Bind pattern: inherits sub-pattern score
            .bind_pattern => |b| self.specificityScore(b.subpat.*),

            // Wildcard is least specific
            .wildcard => 0,
        };
    }

    /// Generate a constructor function for a given term.
    /// Constructors build values from components.
    pub fn genConstructor(
        self: *Self,
        term_id: sema.TermId,
        rule_indices: []const usize,
    ) !void {
        const writer = self.output.writer(self.allocator);
        const term = self.termenv.getTerm(term_id);
        const term_name = self.typeenv.symName(term.name);

        const decl = switch (term.kind) {
            .decl => |d| d,
            else => return error.NotAConstructor,
        };

        // Function signature
        try writer.writeAll("\n/// Constructor for ");
        try writer.writeAll(term_name);
        try writer.writeAll("\n");
        try writer.writeAll("pub fn ");
        try self.writePref(writer, "constructor_", term_name);
        try writer.writeAll("(\n");
        try writer.writeAll("    ctx: *Context,\n");

        // Parameters
        for (decl.arg_tys, 0..) |arg_ty, i| {
            try writer.print("    arg{d}: ", .{i});
            try self.writeTy(writer, arg_ty);
            try writer.writeAll(",\n");
        }

        // Return type
        if (decl.partial) {
            try writer.writeAll(") !?");
            try self.writeTy(writer, decl.ret_ty);
            try writer.writeAll(" {\n");
        } else {
            try writer.writeAll(") !");
            try self.writeTy(writer, decl.ret_ty);
            try writer.writeAll(" {\n");
        }

        // Emit rule matching logic
        if (rule_indices.len > 0) {
            for (rule_indices) |rule_idx| {
                const rule = self.rules[rule_idx];
                try self.emitRuleBody(rule, 4);
            }
        }

        // Default: error for no match
        if (decl.partial) {
            try writer.writeAll("    return null;\n");
        } else {
            try writer.writeAll("    return error.NoMatch;\n");
        }

        try writer.writeAll("}\n");
    }

    /// Generate an extractor function for a given term.
    /// Extractors decompose values and can fail.
    pub fn genExtractor(
        self: *Self,
        term_id: sema.TermId,
        rule_indices: []const usize,
    ) !void {
        const writer = self.output.writer(self.allocator);
        const term = self.termenv.getTerm(term_id);
        const term_name = self.typeenv.symName(term.name);

        const extractor = switch (term.kind) {
            .extractor => |e| e,
            else => return error.NotAnExtractor,
        };

        // Function signature
        try writer.writeAll("\n/// Extractor for ");
        try writer.writeAll(term_name);
        try writer.writeAll("\n");
        try writer.writeAll("pub fn ");
        try self.writePref(writer, "extractor_", term_name);
        try writer.writeAll("(\n");
        try writer.writeAll("    ctx: *Context,\n");

        // Input parameter
        try writer.writeAll("    input: ");
        try self.writeTy(writer, extractor.ret_ty);
        try writer.writeAll(",\n");

        // Parameters
        for (extractor.arg_tys, 0..) |arg_ty, i| {
            try writer.print("    arg{d}: ", .{i});
            try self.writeTy(writer, arg_ty);
            try writer.writeAll(",\n");
        }

        // Return type (fallible)
        try writer.writeAll(") ?");
        try self.writeTy(writer, extractor.ret_ty);
        try writer.writeAll(" {\n");

        // Emit extraction logic
        if (rule_indices.len > 0) {
            for (rule_indices) |rule_idx| {
                const rule = self.rules[rule_idx];
                try self.emitRuleBody(rule, 4);
            }
        }

        // Default: null for failed extraction
        try writer.writeAll("    return null;\n");
        try writer.writeAll("}\n");
    }

    /// Generate the main lowering dispatch function.
    pub fn genLower(self: *Self, term_rules: std.AutoHashMap(sema.TermId, std.ArrayList(usize))) !void {
        const writer = self.output.writer(self.allocator);

        try writer.writeAll(
            \\
            \\/// Main lowering entry point
            \\pub fn lower(ctx: *Context, value: Value) !LoweredValue {
            \\    return switch (value.op) {
            \\
        );

        var it = term_rules.iterator();
        while (it.next()) |entry| {
            const term_id = entry.key_ptr.*;
            _ = entry.value_ptr.items; // rule_indices not used yet

            const term = self.termenv.getTerm(term_id);
            const term_name = self.typeenv.symName(term.name);

            const arg_tys = switch (term.kind) {
                .decl => |d| d.arg_tys,
                else => continue,
            };

            try writer.writeAll("        ");
            try self.writeEnumLit(writer, term_name);
            try writer.writeAll(" => {\n");

            // Extract operands
            for (arg_tys, 0..) |_, i| {
                try writer.print("            const arg{d} = value.operand({d});\n", .{ i, i });
            }

            // Call constructor
            try writer.writeAll("            return ");
            try self.writePref(writer, "constructor_", term_name);
            try writer.writeAll("(ctx");
            for (0..arg_tys.len) |i| {
                try writer.print(", arg{d}", .{i});
            }
            try writer.writeAll(");\n");
            try writer.writeAll("        },\n");
        }

        try writer.writeAll(
            \\        else => return error.UnsupportedOperation,
            \\    };
            \\}
            \\
        );
    }

    /// Get the Zig type name for a type ID.
    fn getTypeName(self: *const Self, type_id: sema.TypeId) ![]const u8 {
        const ty = self.typeenv.types.items[type_id.index()];
        return switch (ty) {
            .primitive => |p| self.typeenv.symName(p.name),
            .tuple => |t| self.typeenv.symName(t.name),
            .enum_type => |e| self.typeenv.symName(e.name),
            else => "Value",
        };
    }

    fn writeIdent(self: *const Self, writer: anytype, name: []const u8) !void {
        _ = self;
        try ident.writeIdent(writer, name);
    }

    fn writeTy(self: *const Self, writer: anytype, type_id: sema.TypeId) !void {
        const name = try self.getTypeName(type_id);
        try self.writeIdent(writer, name);
    }

    fn writePref(self: *const Self, writer: anytype, prefix: []const u8, name: []const u8) !void {
        const full = try std.fmt.allocPrint(self.allocator, "{s}{s}", .{ prefix, name });
        defer self.allocator.free(full);
        try self.writeIdent(writer, full);
    }

    fn writeEnumLit(self: *const Self, writer: anytype, name: []const u8) !void {
        _ = self;
        try ident.writeEnumLit(writer, name);
    }

    fn emitExtractorOutType(
        self: *const Self,
        writer: anytype,
        arg_tys: []const sema.TypeId,
        ret_ty: sema.TypeId,
    ) !void {
        if (arg_tys.len == 0) {
            try self.writeTy(writer, ret_ty);
            return;
        }

        try writer.writeAll("struct { ");
        for (arg_tys, 0..) |arg_ty, i| {
            if (i > 0) try writer.writeAll(", ");
            try writer.print("arg{d}: ", .{i});
            try self.writeTy(writer, arg_ty);
        }
        try writer.writeAll(" }");
    }
};

test "Codegen basic structure" {
    var typeenv = try sema.TypeEnv.init(testing.allocator);
    defer typeenv.deinit();

    var termenv = sema.TermEnv.init(testing.allocator);
    defer termenv.deinit();

    // Create a simple type
    const i32_sym = try typeenv.internSym("i32");
    const i32_ty = typeenv.lookupType(i32_sym) orelse return error.UndefinedType;

    // Create a term: iadd(i32, i32) -> i32
    const iadd_sym = try typeenv.internSym("iadd");
    const iadd_term = sema.Term{
        .name = iadd_sym,
        .id = sema.TermId.new(0),
        .kind = .{ .decl = .{
            .arg_tys = @constCast(&[_]sema.TypeId{ i32_ty, i32_ty }),
            .ret_ty = i32_ty,
            .pure = true,
            .partial = false,
        } },
        .pos = sema.Pos.new(0, 0),
    };
    _ = try termenv.addTerm(iadd_term);

    // Create a simple rule: (iadd x y) => (iadd y x)
    const x_sym = try typeenv.internSym("x");
    const y_sym = try typeenv.internSym("y");

    const pattern = sema.Pattern{ .term = .{
        .term_id = sema.TermId.new(0),
        .args = @constCast(&[_]sema.Pattern{
            .{ .var_pat = .{
                .var_id = 0,
                .name = x_sym,
                .ty = i32_ty,
                .pos = sema.Pos.new(0, 0),
            } },
            .{ .var_pat = .{
                .var_id = 1,
                .name = y_sym,
                .ty = i32_ty,
                .pos = sema.Pos.new(0, 0),
            } },
        }),
        .ty = i32_ty,
        .pos = sema.Pos.new(0, 0),
    } };

    const expr = sema.Expr{ .term = .{
        .term_id = sema.TermId.new(0),
        .args = @constCast(&[_]sema.Expr{
            .{ .var_expr = .{
                .var_id = 1,
                .name = y_sym,
                .ty = i32_ty,
                .pos = sema.Pos.new(0, 0),
            } },
            .{ .var_expr = .{
                .var_id = 0,
                .name = x_sym,
                .ty = i32_ty,
                .pos = sema.Pos.new(0, 0),
            } },
        }),
        .ty = i32_ty,
        .pos = sema.Pos.new(0, 0),
    } };

    const rule = sema.Rule{
        .pattern = pattern,
        .iflets = @constCast(&[0]sema.IfLet{}),
        .expr = expr,
        .prio = 0,
        .pos = sema.Pos.new(0, 0),
    };

    const rules = [_]sema.Rule{rule};

    var codegen = Codegen.init(testing.allocator, &typeenv, &termenv, &rules);
    defer codegen.deinit();

    const code = try codegen.generate(.{});

    // Check that code contains basic structure
    try testing.expect(std.mem.indexOf(u8, code, "pub fn iadd") != null);
    try testing.expect(std.mem.indexOf(u8, code, "arg0: i32") != null);
    try testing.expect(std.mem.indexOf(u8, code, "arg1: i32") != null);
}

test "Codegen emits tuple types" {
    var typeenv = try sema.TypeEnv.init(testing.allocator);
    defer typeenv.deinit();

    var termenv = sema.TermEnv.init(testing.allocator);
    defer termenv.deinit();

    const i32_sym = try typeenv.internSym("i32");
    const i32_ty = typeenv.lookupType(i32_sym) orelse return error.UndefinedType;

    const tuple_id = sema.TypeId.new(@intCast(typeenv.types.items.len));
    const tuple_sym = try typeenv.internSym("tuple_test");
    const fields = try testing.allocator.dupe(sema.TypeId, &[_]sema.TypeId{ i32_ty, i32_ty });
    defer testing.allocator.free(fields);
    _ = try typeenv.addType(.{ .tuple = .{
        .id = tuple_id,
        .name = tuple_sym,
        .fields = fields,
        .pos = sema.Pos.new(0, 0),
    } });

    var gen = Codegen.init(testing.allocator, &typeenv, &termenv, &[_]sema.Rule{});
    defer gen.deinit();

    const code = try gen.generate(.{});
    try testing.expect(std.mem.indexOf(u8, code, "pub const tuple_test") != null);
    try testing.expect(std.mem.indexOf(u8, code, "field0: i32") != null);
    try testing.expect(std.mem.indexOf(u8, code, "field1: i32") != null);
}

test "Codegen extern extractor wrapper signature" {
    var typeenv = try sema.TypeEnv.init(testing.allocator);
    defer typeenv.deinit();

    var termenv = sema.TermEnv.init(testing.allocator);
    defer termenv.deinit();

    const i32_sym = try typeenv.internSym("i32");
    const i64_sym = try typeenv.internSym("i64");
    const i32_ty = typeenv.lookupType(i32_sym) orelse return error.UndefinedType;
    const i64_ty = typeenv.lookupType(i64_sym) orelse return error.UndefinedType;

    const term_sym = try typeenv.internSym("ext_term");
    const term = sema.Term{
        .name = term_sym,
        .id = sema.TermId.new(0),
        .kind = .{ .decl = .{
            .arg_tys = @constCast(&[_]sema.TypeId{ i32_ty, i64_ty }),
            .ret_ty = i32_ty,
            .pure = true,
            .partial = false,
        } },
        .pos = sema.Pos.new(0, 0),
    };
    const term_id = try termenv.addTerm(term);

    const func_sym = try typeenv.internSym("ext_impl");
    try termenv.addExtern(term_id, .extractor, func_sym);

    var gen = Codegen.init(testing.allocator, &typeenv, &termenv, &[_]sema.Rule{});
    defer gen.deinit();

    const code = try gen.generate(.{});

    try testing.expect(std.mem.indexOf(u8, code, "pub fn ext_impl") != null);
    try testing.expect(std.mem.indexOf(u8, code, "input: i32") != null);
    try testing.expect(std.mem.indexOf(u8, code, "!?struct { arg0: i32, arg1: i64 }") != null);
    try testing.expect(std.mem.indexOf(u8, code, "pub fn extractor_ext_term") != null);
}
